spring.application.name=spring-ai-rag-pgvector

server.port=6789
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=postgres
spring.datasource.password=sisu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Ollama Config
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:3b
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.embedding.options.model=nomic-embed-text

#Automatics table creation
spring.ai.vectorstore.pgvector.initialize-schema=true

#Spring AI the size of the embedding vectors(nomic-embed-text is 768)
spring.ai.vectorstore.pgvector.dimensions=768

#File size
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#Actuator Config
management.endpoints.web.exposure.include=*

